stages:
  - publish
  - build
  - deploy

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

build_image:
  stage: build
  only:
    refs:
      - /^(main|develop.*)$/
  tags:
    - imagesbuilder
  script:
    - chmod +x ./ci/deliver.sh
    - ./ci/deliver.sh

deploy_image:
  stage: deploy
  needs:
    - build_image
  script:
    - chmod +x ./ci/deploy.sh
    - ./ci/deploy.sh
  only:
    refs:
      - /^(main|develop.*)$/
  tags:
    - web
