ARG NGINX_VERSION="alpine"

FROM nginx:${NGINX_VERSION} AS ui_run

COPY .docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY .docker/docker-entrypoint.sh /docker-entrypoint.sh

COPY build/web /usr/share/nginx/html

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD [ "nginx", "-g","daemon off;" ]
