name: my_flutter_app
description: A minimal Flutter app with a single main.dart file.

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-comwork.png
  fonts: []
