name: my_flutter_app
description: A minimal Flutter app with a single main.dart file.

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: []
  fonts: []
